//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ar_file {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ar_file() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POS.ar_file", typeof(ar_file).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحاسبة.
        /// </summary>
        internal static string trAccounting {
            get {
                return ResourceManager.GetString("trAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحسابات.
        /// </summary>
        internal static string trAccounts {
            get {
                return ResourceManager.GetString("trAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string trAdd {
            get {
                return ResourceManager.GetString("trAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان....
        /// </summary>
        internal static string trAdressHint {
            get {
                return ResourceManager.GetString("trAdressHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات أخرى.
        /// </summary>
        internal static string trAnotherInfomation {
            get {
                return ResourceManager.GetString("trAnotherInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنطقة....
        /// </summary>
        internal static string trAreaHint {
            get {
                return ResourceManager.GetString("trAreaHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرصيد.
        /// </summary>
        internal static string trBalance {
            get {
                return ResourceManager.GetString("trBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرصيد....
        /// </summary>
        internal static string trBalanceHint {
            get {
                return ResourceManager.GetString("trBalanceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البنوك.
        /// </summary>
        internal static string trBanks {
            get {
                return ResourceManager.GetString("trBanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلومات الأساسية.
        /// </summary>
        internal static string trBaseInformation {
            get {
                return ResourceManager.GetString("trBaseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفروع.
        /// </summary>
        internal static string trBranches {
            get {
                return ResourceManager.GetString("trBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفهرس.
        /// </summary>
        internal static string trCatalog {
            get {
                return ResourceManager.GetString("trCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشركة.
        /// </summary>
        internal static string trCompany {
            get {
                return ResourceManager.GetString("trCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشركة....
        /// </summary>
        internal static string trCompanyHint {
            get {
                return ResourceManager.GetString("trCompanyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string trCompanyName {
            get {
                return ResourceManager.GetString("trCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات التواصل.
        /// </summary>
        internal static string trContactInformation {
            get {
                return ResourceManager.GetString("trContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملاء.
        /// </summary>
        internal static string trCustomers {
            get {
                return ResourceManager.GetString("trCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string trDelete {
            get {
                return ResourceManager.GetString("trDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        internal static string trDetails {
            get {
                return ResourceManager.GetString("trDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل....
        /// </summary>
        internal static string trDetailsHint {
            get {
                return ResourceManager.GetString("trDetailsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني....
        /// </summary>
        internal static string trEmailHint {
            get {
                return ResourceManager.GetString("trEmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول ....
        /// </summary>
        internal static string trFirstNameHint {
            get {
                return ResourceManager.GetString("trFirstNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string trHome {
            get {
                return ResourceManager.GetString("trHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمل.
        /// </summary>
        internal static string trJob {
            get {
                return ResourceManager.GetString("trJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمل ....
        /// </summary>
        internal static string trJobHint {
            get {
                return ResourceManager.GetString("trJobHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكنية ....
        /// </summary>
        internal static string trLastNameHint {
            get {
                return ResourceManager.GetString("trLastNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات التسجيل.
        /// </summary>
        internal static string trLoginInformation {
            get {
                return ResourceManager.GetString("trLoginInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة.
        /// </summary>
        internal static string trMenu {
            get {
                return ResourceManager.GetString("trMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجوال.
        /// </summary>
        internal static string trMobile {
            get {
                return ResourceManager.GetString("trMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجوال....
        /// </summary>
        internal static string trMobileHint {
            get {
                return ResourceManager.GetString("trMobileHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string trName {
            get {
                return ResourceManager.GetString("trName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم....
        /// </summary>
        internal static string trNameHint {
            get {
                return ResourceManager.GetString("trNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات....
        /// </summary>
        internal static string trNoteHint {
            get {
                return ResourceManager.GetString("trNoteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر طريقة الدفع....
        /// </summary>
        internal static string trPamentMethodHint {
            get {
                return ResourceManager.GetString("trPamentMethodHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور ....
        /// </summary>
        internal static string trPasswordHint {
            get {
                return ResourceManager.GetString("trPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف....
        /// </summary>
        internal static string trPhoneHint {
            get {
                return ResourceManager.GetString("trPhoneHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقطة بيع.
        /// </summary>
        internal static string trPOS {
            get {
                return ResourceManager.GetString("trPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشتريات.
        /// </summary>
        internal static string trPurchases {
            get {
                return ResourceManager.GetString("trPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقارير.
        /// </summary>
        internal static string trReports {
            get {
                return ResourceManager.GetString("trReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبيعات.
        /// </summary>
        internal static string trSales {
            get {
                return ResourceManager.GetString("trSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل هنا للبدء بالبحث....
        /// </summary>
        internal static string trSearchHint {
            get {
                return ResourceManager.GetString("trSearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الأساسية.
        /// </summary>
        internal static string trSectionData {
            get {
                return ResourceManager.GetString("trSectionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر عمل ....
        /// </summary>
        internal static string trSelectJobHint {
            get {
                return ResourceManager.GetString("trSelectJobHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعدادت.
        /// </summary>
        internal static string trSettings {
            get {
                return ResourceManager.GetString("trSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخزين.
        /// </summary>
        internal static string trStorage {
            get {
                return ResourceManager.GetString("trStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المخازن.
        /// </summary>
        internal static string trStores {
            get {
                return ResourceManager.GetString("trStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزودون.
        /// </summary>
        internal static string trSuppliers {
            get {
                return ResourceManager.GetString("trSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدات.
        /// </summary>
        internal static string trUnits {
            get {
                return ResourceManager.GetString("trUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        internal static string trUpdate {
            get {
                return ResourceManager.GetString("trUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات المستخدم.
        /// </summary>
        internal static string trUserInformation {
            get {
                return ResourceManager.GetString("trUserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        internal static string trUserName {
            get {
                return ResourceManager.GetString("trUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم ....
        /// </summary>
        internal static string trUserNameHint {
            get {
                return ResourceManager.GetString("trUserNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمون.
        /// </summary>
        internal static string trUsers {
            get {
                return ResourceManager.GetString("trUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستخدم.
        /// </summary>
        internal static string trUserType {
            get {
                return ResourceManager.GetString("trUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات العمل.
        /// </summary>
        internal static string trWorkHours {
            get {
                return ResourceManager.GetString("trWorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات العمل ....
        /// </summary>
        internal static string trWorkHoursHint {
            get {
                return ResourceManager.GetString("trWorkHoursHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات العمل.
        /// </summary>
        internal static string trWorkInformation {
            get {
                return ResourceManager.GetString("trWorkInformation", resourceCulture);
            }
        }
    }
}
