//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ar_file {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ar_file() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POS.ar_file", typeof(ar_file).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحساب.
        /// </summary>
        internal static string trAccNumber {
            get {
                return ResourceManager.GetString("trAccNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحساب....
        /// </summary>
        internal static string trAccNumberHint {
            get {
                return ResourceManager.GetString("trAccNumberHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحاسبة.
        /// </summary>
        internal static string trAccounting {
            get {
                return ResourceManager.GetString("trAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحسابات.
        /// </summary>
        internal static string trAccounts {
            get {
                return ResourceManager.GetString("trAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل.
        /// </summary>
        internal static string trActive {
            get {
                return ResourceManager.GetString("trActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string trAdd {
            get {
                return ResourceManager.GetString("trAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        internal static string trAddress {
            get {
                return ResourceManager.GetString("trAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان....
        /// </summary>
        internal static string trAdressHint {
            get {
                return ResourceManager.GetString("trAdressHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية.
        /// </summary>
        internal static string trAmount {
            get {
                return ResourceManager.GetString("trAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات أخرى.
        /// </summary>
        internal static string trAnotherInfomation {
            get {
                return ResourceManager.GetString("trAnotherInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 963+.
        /// </summary>
        internal static string trAreaHint {
            get {
                return ResourceManager.GetString("trAreaHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرصيد.
        /// </summary>
        internal static string trBalance {
            get {
                return ResourceManager.GetString("trBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرصيد....
        /// </summary>
        internal static string trBalanceHint {
            get {
                return ResourceManager.GetString("trBalanceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البنك.
        /// </summary>
        internal static string trBank {
            get {
                return ResourceManager.GetString("trBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم البنك.
        /// </summary>
        internal static string trBankName {
            get {
                return ResourceManager.GetString("trBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم البنك....
        /// </summary>
        internal static string trBankNameHint {
            get {
                return ResourceManager.GetString("trBankNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البنوك.
        /// </summary>
        internal static string trBanks {
            get {
                return ResourceManager.GetString("trBanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباركود.
        /// </summary>
        internal static string trBarcode {
            get {
                return ResourceManager.GetString("trBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباركود....
        /// </summary>
        internal static string trBarcodeHint {
            get {
                return ResourceManager.GetString("trBarcodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلومات الأساسية.
        /// </summary>
        internal static string trBaseInformation {
            get {
                return ResourceManager.GetString("trBaseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع.
        /// </summary>
        internal static string trBranch {
            get {
                return ResourceManager.GetString("trBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شيفرة الفرع....
        /// </summary>
        internal static string trBranchCodeHint {
            get {
                return ResourceManager.GetString("trBranchCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفروع.
        /// </summary>
        internal static string trBranches {
            get {
                return ResourceManager.GetString("trBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع....
        /// </summary>
        internal static string trBranchHint {
            get {
                return ResourceManager.GetString("trBranchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفرع.
        /// </summary>
        internal static string trBranchName {
            get {
                return ResourceManager.GetString("trBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفرع....
        /// </summary>
        internal static string trBranchNameHint {
            get {
                return ResourceManager.GetString("trBranchNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقدي.
        /// </summary>
        internal static string trCash {
            get {
                return ResourceManager.GetString("trCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفهرس.
        /// </summary>
        internal static string trCatalog {
            get {
                return ResourceManager.GetString("trCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة.
        /// </summary>
        internal static string trCategorie {
            get {
                return ResourceManager.GetString("trCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئات.
        /// </summary>
        internal static string trCategories {
            get {
                return ResourceManager.GetString("trCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفريغ.
        /// </summary>
        internal static string trClear {
            get {
                return ResourceManager.GetString("trClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود.
        /// </summary>
        internal static string trCode {
            get {
                return ResourceManager.GetString("trCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود....
        /// </summary>
        internal static string trCodeHint {
            get {
                return ResourceManager.GetString("trCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشركة.
        /// </summary>
        internal static string trCompany {
            get {
                return ResourceManager.GetString("trCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشركة....
        /// </summary>
        internal static string trCompanyHint {
            get {
                return ResourceManager.GetString("trCompanyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string trCompanyName {
            get {
                return ResourceManager.GetString("trCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات التواصل.
        /// </summary>
        internal static string trContactInformation {
            get {
                return ResourceManager.GetString("trContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كوبون....
        /// </summary>
        internal static string trCoponHint {
            get {
                return ResourceManager.GetString("trCoponHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد السجلات.
        /// </summary>
        internal static string trCount {
            get {
                return ResourceManager.GetString("trCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العدد....
        /// </summary>
        internal static string trCountHint {
            get {
                return ResourceManager.GetString("trCountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الوحدة.
        /// </summary>
        internal static string trCountUnit {
            get {
                return ResourceManager.GetString("trCountUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكوبون.
        /// </summary>
        internal static string trCoupon {
            get {
                return ResourceManager.GetString("trCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الكوبون....
        /// </summary>
        internal static string trCouponCodeHint {
            get {
                return ResourceManager.GetString("trCouponCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الكوبون....
        /// </summary>
        internal static string trCouponNameHint {
            get {
                return ResourceManager.GetString("trCouponNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بطاقة ائتمان.
        /// </summary>
        internal static string trCreditCard {
            get {
                return ResourceManager.GetString("trCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العميل.
        /// </summary>
        internal static string trCustomer {
            get {
                return ResourceManager.GetString("trCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العميل....
        /// </summary>
        internal static string trCustomerHint {
            get {
                return ResourceManager.GetString("trCustomerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملاء.
        /// </summary>
        internal static string trCustomers {
            get {
                return ResourceManager.GetString("trCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string trDelete {
            get {
                return ResourceManager.GetString("trDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوصيل.
        /// </summary>
        internal static string trDelivery {
            get {
                return ResourceManager.GetString("trDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوصيل....
        /// </summary>
        internal static string trDeliveryHint {
            get {
                return ResourceManager.GetString("trDeliveryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإستحقاق....
        /// </summary>
        internal static string trDeservedDateHint {
            get {
                return ResourceManager.GetString("trDeservedDateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستحق....
        /// </summary>
        internal static string trDeservedHint {
            get {
                return ResourceManager.GetString("trDeservedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        internal static string trDetails {
            get {
                return ResourceManager.GetString("trDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل....
        /// </summary>
        internal static string trDetailsHint {
            get {
                return ResourceManager.GetString("trDetailsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحسم.
        /// </summary>
        internal static string trDiscount {
            get {
                return ResourceManager.GetString("trDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحسم....
        /// </summary>
        internal static string trDiscountHint {
            get {
                return ResourceManager.GetString("trDiscountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الحسم.
        /// </summary>
        internal static string trDiscountType {
            get {
                return ResourceManager.GetString("trDiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الحسم.
        /// </summary>
        internal static string trDiscountValue {
            get {
                return ResourceManager.GetString("trDiscountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الحسم....
        /// </summary>
        internal static string trDiscountValueHint {
            get {
                return ResourceManager.GetString("trDiscountValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسودة.
        /// </summary>
        internal static string trDraft {
            get {
                return ResourceManager.GetString("trDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البار كود محجوز مسبقاً.
        /// </summary>
        internal static string trDuplicateBarcodeToolTip {
            get {
                return ResourceManager.GetString("trDuplicateBarcodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز غير صالح.
        /// </summary>
        internal static string trDuplicateCodeToolTip {
            get {
                return ResourceManager.GetString("trDuplicateCodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        internal static string trEmail {
            get {
                return ResourceManager.GetString("trEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني....
        /// </summary>
        internal static string trEmailHint {
            get {
                return ResourceManager.GetString("trEmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحساب لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyAccNumberToolTip {
            get {
                return ResourceManager.GetString("trEmptyAccNumberToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحساب لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyAccNumToolTip {
            get {
                return ResourceManager.GetString("trEmptyAccNumToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر منطقة.
        /// </summary>
        internal static string trEmptyAreaToolTip {
            get {
                return ResourceManager.GetString("trEmptyAreaToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرصيد لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyBalanceToolTip {
            get {
                return ResourceManager.GetString("trEmptyBalanceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباركود لايمكن ان يكون فارغ.
        /// </summary>
        internal static string trEmptyBarcodeToolTip {
            get {
                return ResourceManager.GetString("trEmptyBarcodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع لا يمكن أن يكون فارغاً.
        /// </summary>
        internal static string trEmptyBranchToolTip {
            get {
                return ResourceManager.GetString("trEmptyBranchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyCodeToolTip {
            get {
                return ResourceManager.GetString("trEmptyCodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الحسم لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyDiscountTypeToolTip {
            get {
                return ResourceManager.GetString("trEmptyDiscountTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الحسم لا يمكن أن تكون فارغة.
        /// </summary>
        internal static string trEmptyDiscountValueToolTip {
            get {
                return ResourceManager.GetString("trEmptyDiscountValueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الانتهاء لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyEndDateToolTip {
            get {
                return ResourceManager.GetString("trEmptyEndDateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الانتهاء لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyEndTimeToolTip {
            get {
                return ResourceManager.GetString("trEmptyEndTimeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمل لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyJobToolTip {
            get {
                return ResourceManager.GetString("trEmptyJobToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأخير لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyLastNameToolTip {
            get {
                return ResourceManager.GetString("trEmptyLastNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة العليا للفاتورة لا يمكن أن تكون فارغة.
        /// </summary>
        internal static string trEmptyMaxInvoiceValueToolTip {
            get {
                return ResourceManager.GetString("trEmptyMaxInvoiceValueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة الدنيا للفاتورة لا يمكن أن تكون فارغة.
        /// </summary>
        internal static string trEmptyMinInvoiceValueToolTip {
            get {
                return ResourceManager.GetString("trEmptyMinInvoiceValueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل رقم الجوال.
        /// </summary>
        internal static string trEmptyMobileToolTip {
            get {
                return ResourceManager.GetString("trEmptyMobileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyNameToolTip {
            get {
                return ResourceManager.GetString("trEmptyNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور لا يمكن أن تكون فارغة.
        /// </summary>
        internal static string trEmptyPasswordToolTip {
            get {
                return ResourceManager.GetString("trEmptyPasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن أن يكون رقم الهاتف فارغ.
        /// </summary>
        internal static string trEmptyPhoneToolTip {
            get {
                return ResourceManager.GetString("trEmptyPhoneToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخاصية لا يمكن أن تكون فارغة.
        /// </summary>
        internal static string trEmptyPropertyToolTip {
            get {
                return ResourceManager.GetString("trEmptyPropertyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية لا يمكن أن تكون فارغة.
        /// </summary>
        internal static string trEmptyQuantityToolTip {
            get {
                return ResourceManager.GetString("trEmptyQuantityToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البدء لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyStartDateToolTip {
            get {
                return ResourceManager.GetString("trEmptyStartDateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البدء لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyStartTimeToolTip {
            get {
                return ResourceManager.GetString("trEmptyStartTimeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم لا بمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyUserNameToolTip {
            get {
                return ResourceManager.GetString("trEmptyUserNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة لا يمكن أن تكون فارغة.
        /// </summary>
        internal static string trEmptyValueToolTip {
            get {
                return ResourceManager.GetString("trEmptyValueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهاية.
        /// </summary>
        internal static string trEndDate {
            get {
                return ResourceManager.GetString("trEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهاية....
        /// </summary>
        internal static string trEndDateHint {
            get {
                return ResourceManager.GetString("trEndDateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الانتهاء.
        /// </summary>
        internal static string trEndTime {
            get {
                return ResourceManager.GetString("trEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباركود محجوز مسبقاً.
        /// </summary>
        internal static string trErrorDuplicateBarcodeToolTip {
            get {
                return ResourceManager.GetString("trErrorDuplicateBarcodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الوحدة محجوز مسبقاً.
        /// </summary>
        internal static string trErrorDuplicateUnitNameToolTip {
            get {
                return ResourceManager.GetString("trErrorDuplicateUnitNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم محجوز مسبقاً.
        /// </summary>
        internal static string trErrorDuplicateUserNameToolTip {
            get {
                return ResourceManager.GetString("trErrorDuplicateUserNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان البريد غير صالح.
        /// </summary>
        internal static string trErrorEmailToolTip {
            get {
                return ResourceManager.GetString("trErrorEmailToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباركود لا يمكن أن يكون فارغاً.
        /// </summary>
        internal static string trErrorEmptyBarcodeToolTip {
            get {
                return ResourceManager.GetString("trErrorEmptyBarcodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة لا يمكن أن تكون فارغة.
        /// </summary>
        internal static string trErrorEmptyCategoryToolTip {
            get {
                return ResourceManager.GetString("trErrorEmptyCategoryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العدد لا يمكن أن يكون فارغاً.
        /// </summary>
        internal static string trErrorEmptyCountToolTip {
            get {
                return ResourceManager.GetString("trErrorEmptyCountToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأعلى لا يمكن أن يكون فارغاً.
        /// </summary>
        internal static string trErrorEmptyMaxToolTip {
            get {
                return ResourceManager.GetString("trErrorEmptyMaxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأدنى لايمكن أن يكون فارغاً.
        /// </summary>
        internal static string trErrorEmptyMinToolTip {
            get {
                return ResourceManager.GetString("trErrorEmptyMinToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر لا يمكن أن يكون فارغاً.
        /// </summary>
        internal static string trErrorEmptyPriceToolTip {
            get {
                return ResourceManager.GetString("trErrorEmptyPriceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trErrorEmptyTypeToolTip {
            get {
                return ResourceManager.GetString("trErrorEmptyTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة لا يمكن أن تكون فارغة.
        /// </summary>
        internal static string trErrorEmptyUnitToolTip {
            get {
                return ResourceManager.GetString("trErrorEmptyUnitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المورد لا يمكن أن يكون فارغاً.
        /// </summary>
        internal static string trErrorEmptyVendorToolTip {
            get {
                return ResourceManager.GetString("trErrorEmptyVendorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن أن يكون تاريخ الانتهاء أقدم من تاريخ البدء.
        /// </summary>
        internal static string trErrorEndDateSmallerToolTip {
            get {
                return ResourceManager.GetString("trErrorEndDateSmallerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت الانتهاء لا يمكن أن يكون قبل وقت الابتداء.
        /// </summary>
        internal static string trErrorEndTimeSmallerToolTip {
            get {
                return ResourceManager.GetString("trErrorEndTimeSmallerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباركود لا يمكن كتابته بالعربية.
        /// </summary>
        internal static string trErrorEnglishBarcodeToolTip {
            get {
                return ResourceManager.GetString("trErrorEnglishBarcodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنصر غير موجود.
        /// </summary>
        internal static string trErrorItemNotFoundToolTip {
            get {
                return ResourceManager.GetString("trErrorItemNotFoundToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن أن يكون الحد الأعظمي للفاتورة أقل من الحد الأدنى.
        /// </summary>
        internal static string trErrorMaxInvoiceSmallerToolTip {
            get {
                return ResourceManager.GetString("trErrorMaxInvoiceSmallerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن أن تكون كلمة المرور أقل من 6 محارف.
        /// </summary>
        internal static string trErrorPasswordLengthToolTip {
            get {
                return ResourceManager.GetString("trErrorPasswordLengthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصدير إلى ملف إكسل.
        /// </summary>
        internal static string trExcel {
            get {
                return ResourceManager.GetString("trExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفاكس.
        /// </summary>
        internal static string trFax {
            get {
                return ResourceManager.GetString("trFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاكس....
        /// </summary>
        internal static string trFaxHint {
            get {
                return ResourceManager.GetString("trFaxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول....
        /// </summary>
        internal static string trFirstNameHint {
            get {
                return ResourceManager.GetString("trFirstNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string trHome {
            get {
                return ResourceManager.GetString("trHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء التفعيل.
        /// </summary>
        internal static string trInActive {
            get {
                return ResourceManager.GetString("trInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفاتورة.
        /// </summary>
        internal static string trInvoice {
            get {
                return ResourceManager.GetString("trInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الفاتورة....
        /// </summary>
        internal static string trInvoiceDateHint {
            get {
                return ResourceManager.GetString("trInvoiceDateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفاتورة....
        /// </summary>
        internal static string trInvoiceHint {
            get {
                return ResourceManager.GetString("trInvoiceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفاتورة.
        /// </summary>
        internal static string trInvoiceNumber {
            get {
                return ResourceManager.GetString("trInvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفاتورة....
        /// </summary>
        internal static string trInvoiceNumberHint {
            get {
                return ResourceManager.GetString("trInvoiceNumberHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة الافتراضية للبيع.
        /// </summary>
        internal static string trIsDefaultPurchases {
            get {
                return ResourceManager.GetString("trIsDefaultPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة الافتراضية للشراء.
        /// </summary>
        internal static string trIsDefaultSales {
            get {
                return ResourceManager.GetString("trIsDefaultSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هي الوحدة الأصغر.
        /// </summary>
        internal static string trIsSmallest {
            get {
                return ResourceManager.GetString("trIsSmallest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هي الوحدة الأصغر.
        /// </summary>
        internal static string trIsSmallestHint {
            get {
                return ResourceManager.GetString("trIsSmallestHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنصر.
        /// </summary>
        internal static string trItem {
            get {
                return ResourceManager.GetString("trItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات.
        /// </summary>
        internal static string trItemData {
            get {
                return ResourceManager.GetString("trItemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العناصر.
        /// </summary>
        internal static string trItems {
            get {
                return ResourceManager.GetString("trItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمل.
        /// </summary>
        internal static string trJob {
            get {
                return ResourceManager.GetString("trJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمل....
        /// </summary>
        internal static string trJobHint {
            get {
                return ResourceManager.GetString("trJobHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاخير.
        /// </summary>
        internal static string trLastName {
            get {
                return ResourceManager.GetString("trLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكنية....
        /// </summary>
        internal static string trLastNameHint {
            get {
                return ResourceManager.GetString("trLastNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات التسجيل.
        /// </summary>
        internal static string trLoginInformation {
            get {
                return ResourceManager.GetString("trLoginInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخاصية الأساسية.
        /// </summary>
        internal static string trMainProperty {
            get {
                return ResourceManager.GetString("trMainProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل الخاصية الأساسية.
        /// </summary>
        internal static string trMainPropertyHint {
            get {
                return ResourceManager.GetString("trMainPropertyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأكبر.
        /// </summary>
        internal static string trMaxHint {
            get {
                return ResourceManager.GetString("trMaxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أكبر قيمة للفاتورة....
        /// </summary>
        internal static string trMaximumInvoiceValueHint {
            get {
                return ResourceManager.GetString("trMaximumInvoiceValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة العظمى للفاتورة.
        /// </summary>
        internal static string trMaxInvoice {
            get {
                return ResourceManager.GetString("trMaxInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة العظمى للفاتورة.
        /// </summary>
        internal static string trMaxInvoiceValue {
            get {
                return ResourceManager.GetString("trMaxInvoiceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة.
        /// </summary>
        internal static string trMenu {
            get {
                return ResourceManager.GetString("trMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحدود الدنيا والعليا من العنصر.
        /// </summary>
        internal static string trMinAndMaxOfItem {
            get {
                return ResourceManager.GetString("trMinAndMaxOfItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأصغر.
        /// </summary>
        internal static string trMinHint {
            get {
                return ResourceManager.GetString("trMinHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أصغر قيمة للفاتورة....
        /// </summary>
        internal static string trMinimumInvoiceValueHint {
            get {
                return ResourceManager.GetString("trMinimumInvoiceValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة الدنيا للفاتورة.
        /// </summary>
        internal static string trMinInvoice {
            get {
                return ResourceManager.GetString("trMinInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة الدنيا للفاتورة.
        /// </summary>
        internal static string trMinInvoiceValue {
            get {
                return ResourceManager.GetString("trMinInvoiceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجوال.
        /// </summary>
        internal static string trMobile {
            get {
                return ResourceManager.GetString("trMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجوال....
        /// </summary>
        internal static string trMobileHint {
            get {
                return ResourceManager.GetString("trMobileHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات اخرى.
        /// </summary>
        internal static string trMoreInformation {
            get {
                return ResourceManager.GetString("trMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string trName {
            get {
                return ResourceManager.GetString("trName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم....
        /// </summary>
        internal static string trNameHint {
            get {
                return ResourceManager.GetString("trNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        internal static string trNote {
            get {
                return ResourceManager.GetString("trNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات....
        /// </summary>
        internal static string trNoteHint {
            get {
                return ResourceManager.GetString("trNoteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم.
        /// </summary>
        internal static string trNum {
            get {
                return ResourceManager.GetString("trNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العروض.
        /// </summary>
        internal static string trOffer {
            get {
                return ResourceManager.GetString("trOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العناصر.
        /// </summary>
        internal static string trOnItems {
            get {
                return ResourceManager.GetString("trOnItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدفوع....
        /// </summary>
        internal static string trPaidHint {
            get {
                return ResourceManager.GetString("trPaidHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر طريقة الدفع....
        /// </summary>
        internal static string trPamentMethodHint {
            get {
                return ResourceManager.GetString("trPamentMethodHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع الأب.
        /// </summary>
        internal static string trParentBranch {
            get {
                return ResourceManager.GetString("trParentBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر العنصر الأب.
        /// </summary>
        internal static string trParentCategorieHint {
            get {
                return ResourceManager.GetString("trParentCategorieHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة الأب.
        /// </summary>
        internal static string trParentCategory {
            get {
                return ResourceManager.GetString("trParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        internal static string trPassword {
            get {
                return ResourceManager.GetString("trPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور....
        /// </summary>
        internal static string trPasswordHint {
            get {
                return ResourceManager.GetString("trPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة PDF.
        /// </summary>
        internal static string trPdf {
            get {
                return ResourceManager.GetString("trPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        internal static string trPdfBtn {
            get {
                return ResourceManager.GetString("trPdfBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبة مئوية.
        /// </summary>
        internal static string trPercentageDiscount {
            get {
                return ResourceManager.GetString("trPercentageDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف.
        /// </summary>
        internal static string trPhone {
            get {
                return ResourceManager.GetString("trPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف....
        /// </summary>
        internal static string trPhoneHint {
            get {
                return ResourceManager.GetString("trPhoneHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخطط دائري.
        /// </summary>
        internal static string trPieChart {
            get {
                return ResourceManager.GetString("trPieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التفعيل بنجاح.
        /// </summary>
        internal static string trPopActive {
            get {
                return ResourceManager.GetString("trPopActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت الإضافة بنجاح.
        /// </summary>
        internal static string trPopAdd {
            get {
                return ResourceManager.GetString("trPopAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن الإضافة بدون الكود و الاسم و رقم الجوال.
        /// </summary>
        internal static string trPopAddValidate {
            get {
                return ResourceManager.GetString("trPopAddValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البنك موجود مسبقاً.
        /// </summary>
        internal static string trPopBankExist {
            get {
                return ResourceManager.GetString("trPopBankExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح.
        /// </summary>
        internal static string trPopDelete {
            get {
                return ResourceManager.GetString("trPopDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ.
        /// </summary>
        internal static string trPopError {
            get {
                return ResourceManager.GetString("trPopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغاء التفيل بنجاح.
        /// </summary>
        internal static string trPopInActive {
            get {
                return ResourceManager.GetString("trPopInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل بنجاح.
        /// </summary>
        internal static string trPopUpdate {
            get {
                return ResourceManager.GetString("trPopUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن التعديل بدون الاسم و رقم الجوال.
        /// </summary>
        internal static string trPopUpdateValidate {
            get {
                return ResourceManager.GetString("trPopUpdateValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقطة بيع.
        /// </summary>
        internal static string trPOS {
            get {
                return ResourceManager.GetString("trPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز نقطة البيع.
        /// </summary>
        internal static string trPosCode {
            get {
                return ResourceManager.GetString("trPosCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز نقطة البيع....
        /// </summary>
        internal static string trPosCodeHint {
            get {
                return ResourceManager.GetString("trPosCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم نقطة البيع.
        /// </summary>
        internal static string trPosName {
            get {
                return ResourceManager.GetString("trPosName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم نقطة البيع....
        /// </summary>
        internal static string trPosNameHint {
            get {
                return ResourceManager.GetString("trPosNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معاينة.
        /// </summary>
        internal static string trPreview {
            get {
                return ResourceManager.GetString("trPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        internal static string trPrice {
            get {
                return ResourceManager.GetString("trPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر....
        /// </summary>
        internal static string trPriceHint {
            get {
                return ResourceManager.GetString("trPriceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة.
        /// </summary>
        internal static string trPrint {
            get {
                return ResourceManager.GetString("trPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصائص.
        /// </summary>
        internal static string trProperties {
            get {
                return ResourceManager.GetString("trProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشتريات.
        /// </summary>
        internal static string trPurchases {
            get {
                return ResourceManager.GetString("trPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية.
        /// </summary>
        internal static string trQuantity {
            get {
                return ResourceManager.GetString("trQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية....
        /// </summary>
        internal static string trQuantityHint {
            get {
                return ResourceManager.GetString("trQuantityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث.
        /// </summary>
        internal static string trRefresh {
            get {
                return ResourceManager.GetString("trRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية المتبقية.
        /// </summary>
        internal static string trRemainQuantity {
            get {
                return ResourceManager.GetString("trRemainQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية المتبقية....
        /// </summary>
        internal static string trRemainQuantityHint {
            get {
                return ResourceManager.GetString("trRemainQuantityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقارير.
        /// </summary>
        internal static string trReports {
            get {
                return ResourceManager.GetString("trReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة الإرجاع.
        /// </summary>
        internal static string trReturnInvoice {
            get {
                return ResourceManager.GetString("trReturnInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبيعات.
        /// </summary>
        internal static string trSales {
            get {
                return ResourceManager.GetString("trSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        internal static string trSave {
            get {
                return ResourceManager.GetString("trSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        internal static string trSearch {
            get {
                return ResourceManager.GetString("trSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل هنا للبدء بالبحث....
        /// </summary>
        internal static string trSearchHint {
            get {
                return ResourceManager.GetString("trSearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلوامات الثانوية.
        /// </summary>
        internal static string trSecondaryInformation {
            get {
                return ResourceManager.GetString("trSecondaryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الأساسية.
        /// </summary>
        internal static string trSectionData {
            get {
                return ResourceManager.GetString("trSectionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر اسم البنك.
        /// </summary>
        internal static string trSelectBankNameHint {
            get {
                return ResourceManager.GetString("trSelectBankNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع الأب ....
        /// </summary>
        internal static string trSelectBranchHint {
            get {
                return ResourceManager.GetString("trSelectBranchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الفئة.
        /// </summary>
        internal static string trSelectCategorieHint {
            get {
                return ResourceManager.GetString("trSelectCategorieHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر نوع العنصر.
        /// </summary>
        internal static string trSelectItemTypeHint {
            get {
                return ResourceManager.GetString("trSelectItemTypeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر عمل....
        /// </summary>
        internal static string trSelectJobHint {
            get {
                return ResourceManager.GetString("trSelectJobHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر العنصر الأب.
        /// </summary>
        internal static string trSelectParentItemHint {
            get {
                return ResourceManager.GetString("trSelectParentItemHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الفرع.
        /// </summary>
        internal static string trSelectPosBranchHint {
            get {
                return ResourceManager.GetString("trSelectPosBranchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر اسم نقطة البيع.
        /// </summary>
        internal static string trSelectPosNameHint {
            get {
                return ResourceManager.GetString("trSelectPosNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الخصائص.
        /// </summary>
        internal static string trSelectProperties {
            get {
                return ResourceManager.GetString("trSelectProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر اسم الخاصية.
        /// </summary>
        internal static string trSelectPropertyNameHint {
            get {
                return ResourceManager.GetString("trSelectPropertyNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر أصغر وحدة.
        /// </summary>
        internal static string trSelectSmallestUnitHint {
            get {
                return ResourceManager.GetString("trSelectSmallestUnitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر اسم المخزن.
        /// </summary>
        internal static string trSelectStoreHint {
            get {
                return ResourceManager.GetString("trSelectStoreHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الوحدة.
        /// </summary>
        internal static string trSelectUnitHint {
            get {
                return ResourceManager.GetString("trSelectUnitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر اسم الوحدة.
        /// </summary>
        internal static string trSelestUnitNameHint {
            get {
                return ResourceManager.GetString("trSelestUnitNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعدادت.
        /// </summary>
        internal static string trSettings {
            get {
                return ResourceManager.GetString("trSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أصغر وحدة.
        /// </summary>
        internal static string trSmallestUnit {
            get {
                return ResourceManager.GetString("trSmallestUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اصغر وحدة.
        /// </summary>
        internal static string trSmallUnit {
            get {
                return ResourceManager.GetString("trSmallUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البداية.
        /// </summary>
        internal static string trStartDate {
            get {
                return ResourceManager.GetString("trStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البداية....
        /// </summary>
        internal static string trStartDateHint {
            get {
                return ResourceManager.GetString("trStartDateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البدء.
        /// </summary>
        internal static string trStartTime {
            get {
                return ResourceManager.GetString("trStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإحصائيات.
        /// </summary>
        internal static string trStatistic {
            get {
                return ResourceManager.GetString("trStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخزين.
        /// </summary>
        internal static string trStorage {
            get {
                return ResourceManager.GetString("trStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المخزن.
        /// </summary>
        internal static string trStore {
            get {
                return ResourceManager.GetString("trStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شيفرة المخزن....
        /// </summary>
        internal static string trStoreCodeHint {
            get {
                return ResourceManager.GetString("trStoreCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المخزن....
        /// </summary>
        internal static string trStoreNameHint {
            get {
                return ResourceManager.GetString("trStoreNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المخازن.
        /// </summary>
        internal static string trStores {
            get {
                return ResourceManager.GetString("trStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخواص الفرعية.
        /// </summary>
        internal static string trSubProperties {
            get {
                return ResourceManager.GetString("trSubProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل الخاصية الفرعية.
        /// </summary>
        internal static string trSubPropertiesHint {
            get {
                return ResourceManager.GetString("trSubPropertiesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموع.
        /// </summary>
        internal static string trSum {
            get {
                return ResourceManager.GetString("trSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموردون.
        /// </summary>
        internal static string trSuppliers {
            get {
                return ResourceManager.GetString("trSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الضريبة.
        /// </summary>
        internal static string trTax {
            get {
                return ResourceManager.GetString("trTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الضرائب....
        /// </summary>
        internal static string trTaxesHint {
            get {
                return ResourceManager.GetString("trTaxesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجمالي.
        /// </summary>
        internal static string trTotal {
            get {
                return ResourceManager.GetString("trTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجمالي:.
        /// </summary>
        internal static string trTotal_ {
            get {
                return ResourceManager.GetString("trTotal:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الحسم....
        /// </summary>
        internal static string trTypeDiscountHint {
            get {
                return ResourceManager.GetString("trTypeDiscountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة.
        /// </summary>
        internal static string trUnit {
            get {
                return ResourceManager.GetString("trUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة....
        /// </summary>
        internal static string trUnitHint {
            get {
                return ResourceManager.GetString("trUnitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الوحدة.
        /// </summary>
        internal static string trUnitName {
            get {
                return ResourceManager.GetString("trUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الوحدة....
        /// </summary>
        internal static string trUnitNameHint {
            get {
                return ResourceManager.GetString("trUnitNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدات.
        /// </summary>
        internal static string trUnits {
            get {
                return ResourceManager.GetString("trUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        internal static string trUpdate {
            get {
                return ResourceManager.GetString("trUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأعلى للسحب.
        /// </summary>
        internal static string trUpperLimit {
            get {
                return ResourceManager.GetString("trUpperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأعلى للسحب....
        /// </summary>
        internal static string trUpperLimitHint {
            get {
                return ResourceManager.GetString("trUpperLimitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم.
        /// </summary>
        internal static string trUser {
            get {
                return ResourceManager.GetString("trUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات المستخدم.
        /// </summary>
        internal static string trUserInformation {
            get {
                return ResourceManager.GetString("trUserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        internal static string trUserName {
            get {
                return ResourceManager.GetString("trUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم....
        /// </summary>
        internal static string trUserNameHint {
            get {
                return ResourceManager.GetString("trUserNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمون.
        /// </summary>
        internal static string trUsers {
            get {
                return ResourceManager.GetString("trUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستخدم.
        /// </summary>
        internal static string trUserType {
            get {
                return ResourceManager.GetString("trUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة.
        /// </summary>
        internal static string trValue {
            get {
                return ResourceManager.GetString("trValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة.
        /// </summary>
        internal static string trValueDiscount {
            get {
                return ResourceManager.GetString("trValueDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة....
        /// </summary>
        internal static string trValueHint {
            get {
                return ResourceManager.GetString("trValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المورد.
        /// </summary>
        internal static string trVendor {
            get {
                return ResourceManager.GetString("trVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المورد....
        /// </summary>
        internal static string trVendorHint {
            get {
                return ResourceManager.GetString("trVendorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل فاتورة المزود.
        /// </summary>
        internal static string trVendorInvoiceDetails {
            get {
                return ResourceManager.GetString("trVendorInvoiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العرض على شكل قائمة.
        /// </summary>
        internal static string trViewGrid {
            get {
                return ResourceManager.GetString("trViewGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العرض على شكل عناصر.
        /// </summary>
        internal static string trViewItems {
            get {
                return ResourceManager.GetString("trViewItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات العمل.
        /// </summary>
        internal static string trWorkHours {
            get {
                return ResourceManager.GetString("trWorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات العمل....
        /// </summary>
        internal static string trWorkHoursHint {
            get {
                return ResourceManager.GetString("trWorkHoursHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات العمل.
        /// </summary>
        internal static string trWorkInformation {
            get {
                return ResourceManager.GetString("trWorkInformation", resourceCulture);
            }
        }
    }
}
