//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ar_file {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ar_file() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POS.ar_file", typeof(ar_file).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحساب.
        /// </summary>
        internal static string trAccNumber {
            get {
                return ResourceManager.GetString("trAccNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحساب....
        /// </summary>
        internal static string trAccNumberHint {
            get {
                return ResourceManager.GetString("trAccNumberHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحاسبة.
        /// </summary>
        internal static string trAccounting {
            get {
                return ResourceManager.GetString("trAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحسابات.
        /// </summary>
        internal static string trAccounts {
            get {
                return ResourceManager.GetString("trAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string trAdd {
            get {
                return ResourceManager.GetString("trAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        internal static string trAddress {
            get {
                return ResourceManager.GetString("trAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان....
        /// </summary>
        internal static string trAdressHint {
            get {
                return ResourceManager.GetString("trAdressHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات أخرى.
        /// </summary>
        internal static string trAnotherInfomation {
            get {
                return ResourceManager.GetString("trAnotherInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 963+.
        /// </summary>
        internal static string trAreaHint {
            get {
                return ResourceManager.GetString("trAreaHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرصيد.
        /// </summary>
        internal static string trBalance {
            get {
                return ResourceManager.GetString("trBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرصيد....
        /// </summary>
        internal static string trBalanceHint {
            get {
                return ResourceManager.GetString("trBalanceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البنك.
        /// </summary>
        internal static string trBank {
            get {
                return ResourceManager.GetString("trBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم البنك.
        /// </summary>
        internal static string trBankName {
            get {
                return ResourceManager.GetString("trBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم البنك....
        /// </summary>
        internal static string trBankNameHint {
            get {
                return ResourceManager.GetString("trBankNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البنوك.
        /// </summary>
        internal static string trBanks {
            get {
                return ResourceManager.GetString("trBanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباركود.
        /// </summary>
        internal static string trBarcode {
            get {
                return ResourceManager.GetString("trBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباركود....
        /// </summary>
        internal static string trBarcodeHint {
            get {
                return ResourceManager.GetString("trBarcodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلومات الأساسية.
        /// </summary>
        internal static string trBaseInformation {
            get {
                return ResourceManager.GetString("trBaseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع.
        /// </summary>
        internal static string trBranch {
            get {
                return ResourceManager.GetString("trBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شيفرة الفرع....
        /// </summary>
        internal static string trBranchCodeHint {
            get {
                return ResourceManager.GetString("trBranchCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفروع.
        /// </summary>
        internal static string trBranches {
            get {
                return ResourceManager.GetString("trBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفرع.
        /// </summary>
        internal static string trBranchName {
            get {
                return ResourceManager.GetString("trBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفرع....
        /// </summary>
        internal static string trBranchNameHint {
            get {
                return ResourceManager.GetString("trBranchNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفهرس.
        /// </summary>
        internal static string trCatalog {
            get {
                return ResourceManager.GetString("trCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة.
        /// </summary>
        internal static string trCategorie {
            get {
                return ResourceManager.GetString("trCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئات.
        /// </summary>
        internal static string trCategories {
            get {
                return ResourceManager.GetString("trCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفريغ.
        /// </summary>
        internal static string trClear {
            get {
                return ResourceManager.GetString("trClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشيفرة.
        /// </summary>
        internal static string trCode {
            get {
                return ResourceManager.GetString("trCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود....
        /// </summary>
        internal static string trCodeHint {
            get {
                return ResourceManager.GetString("trCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشركة.
        /// </summary>
        internal static string trCompany {
            get {
                return ResourceManager.GetString("trCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشركة....
        /// </summary>
        internal static string trCompanyHint {
            get {
                return ResourceManager.GetString("trCompanyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string trCompanyName {
            get {
                return ResourceManager.GetString("trCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات التواصل.
        /// </summary>
        internal static string trContactInformation {
            get {
                return ResourceManager.GetString("trContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العدد....
        /// </summary>
        internal static string trCountHint {
            get {
                return ResourceManager.GetString("trCountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الوحدة.
        /// </summary>
        internal static string trCountUnit {
            get {
                return ResourceManager.GetString("trCountUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الزبون.
        /// </summary>
        internal static string trCustomer {
            get {
                return ResourceManager.GetString("trCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملاء.
        /// </summary>
        internal static string trCustomers {
            get {
                return ResourceManager.GetString("trCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string trDelete {
            get {
                return ResourceManager.GetString("trDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        internal static string trDetails {
            get {
                return ResourceManager.GetString("trDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل....
        /// </summary>
        internal static string trDetailsHint {
            get {
                return ResourceManager.GetString("trDetailsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني....
        /// </summary>
        internal static string trEmailHint {
            get {
                return ResourceManager.GetString("trEmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحساب لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyAccNumToolTip {
            get {
                return ResourceManager.GetString("trEmptyAccNumToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر منطقة.
        /// </summary>
        internal static string trEmptyAreaToolTip {
            get {
                return ResourceManager.GetString("trEmptyAreaToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرصيد لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyBalanceToolTip {
            get {
                return ResourceManager.GetString("trEmptyBalanceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyCodeToolTip {
            get {
                return ResourceManager.GetString("trEmptyCodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأخير لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyLastNameToolTip {
            get {
                return ResourceManager.GetString("trEmptyLastNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل رقم الجوال.
        /// </summary>
        internal static string trEmptyMobileToolTip {
            get {
                return ResourceManager.GetString("trEmptyMobileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم لا يمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyNameToolTip {
            get {
                return ResourceManager.GetString("trEmptyNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور لا يمكن أن تكون فارغة.
        /// </summary>
        internal static string trEmptyPasswordToolTip {
            get {
                return ResourceManager.GetString("trEmptyPasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم لا بمكن أن يكون فارغ.
        /// </summary>
        internal static string trEmptyUserNameToolTip {
            get {
                return ResourceManager.GetString("trEmptyUserNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان البريد غير صالح.
        /// </summary>
        internal static string trErrorEmailToolTip {
            get {
                return ResourceManager.GetString("trErrorEmailToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاكس....
        /// </summary>
        internal static string trFaxHint {
            get {
                return ResourceManager.GetString("trFaxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول....
        /// </summary>
        internal static string trFirstNameHint {
            get {
                return ResourceManager.GetString("trFirstNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string trHome {
            get {
                return ResourceManager.GetString("trHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة الافتراضية للبيع.
        /// </summary>
        internal static string trIsDefaultPurchases {
            get {
                return ResourceManager.GetString("trIsDefaultPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة الافتراضية للشراء.
        /// </summary>
        internal static string trIsDefaultSales {
            get {
                return ResourceManager.GetString("trIsDefaultSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هي الوحدة الأصغر.
        /// </summary>
        internal static string trIsSmallest {
            get {
                return ResourceManager.GetString("trIsSmallest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هي الوحدة الأصغر.
        /// </summary>
        internal static string trIsSmallestHint {
            get {
                return ResourceManager.GetString("trIsSmallestHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات.
        /// </summary>
        internal static string trItemData {
            get {
                return ResourceManager.GetString("trItemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العناصر.
        /// </summary>
        internal static string trItems {
            get {
                return ResourceManager.GetString("trItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمل.
        /// </summary>
        internal static string trJob {
            get {
                return ResourceManager.GetString("trJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمل....
        /// </summary>
        internal static string trJobHint {
            get {
                return ResourceManager.GetString("trJobHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاخير.
        /// </summary>
        internal static string trLastName {
            get {
                return ResourceManager.GetString("trLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكنية....
        /// </summary>
        internal static string trLastNameHint {
            get {
                return ResourceManager.GetString("trLastNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات التسجيل.
        /// </summary>
        internal static string trLoginInformation {
            get {
                return ResourceManager.GetString("trLoginInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخاصية الأساسية.
        /// </summary>
        internal static string trMainProperty {
            get {
                return ResourceManager.GetString("trMainProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل الخاصية الأساسية.
        /// </summary>
        internal static string trMainPropertyHint {
            get {
                return ResourceManager.GetString("trMainPropertyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأكبر.
        /// </summary>
        internal static string trMaxHint {
            get {
                return ResourceManager.GetString("trMaxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة.
        /// </summary>
        internal static string trMenu {
            get {
                return ResourceManager.GetString("trMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحدود الدنيا والعليا من العنصر.
        /// </summary>
        internal static string trMinAndMaxOfItem {
            get {
                return ResourceManager.GetString("trMinAndMaxOfItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأصغر.
        /// </summary>
        internal static string trMinHint {
            get {
                return ResourceManager.GetString("trMinHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجوال.
        /// </summary>
        internal static string trMobile {
            get {
                return ResourceManager.GetString("trMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجوال....
        /// </summary>
        internal static string trMobileHint {
            get {
                return ResourceManager.GetString("trMobileHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات اخرى.
        /// </summary>
        internal static string trMoreInformation {
            get {
                return ResourceManager.GetString("trMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string trName {
            get {
                return ResourceManager.GetString("trName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم....
        /// </summary>
        internal static string trNameHint {
            get {
                return ResourceManager.GetString("trNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات....
        /// </summary>
        internal static string trNoteHint {
            get {
                return ResourceManager.GetString("trNoteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر طريقة الدفع....
        /// </summary>
        internal static string trPamentMethodHint {
            get {
                return ResourceManager.GetString("trPamentMethodHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر العنصر الأب.
        /// </summary>
        internal static string trParentCategorieHint {
            get {
                return ResourceManager.GetString("trParentCategorieHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور....
        /// </summary>
        internal static string trPasswordHint {
            get {
                return ResourceManager.GetString("trPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف....
        /// </summary>
        internal static string trPhoneHint {
            get {
                return ResourceManager.GetString("trPhoneHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت الإضافة بنجاح.
        /// </summary>
        internal static string trPopAdd {
            get {
                return ResourceManager.GetString("trPopAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن الإضافة بدون الاسم و رقم الجوال.
        /// </summary>
        internal static string trPopAddValidate {
            get {
                return ResourceManager.GetString("trPopAddValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح.
        /// </summary>
        internal static string trPopDelete {
            get {
                return ResourceManager.GetString("trPopDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ.
        /// </summary>
        internal static string trPopError {
            get {
                return ResourceManager.GetString("trPopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل بنجاح.
        /// </summary>
        internal static string trPopUpdate {
            get {
                return ResourceManager.GetString("trPopUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن التعديل بدون الاسم و رقم الجوال.
        /// </summary>
        internal static string trPopUpdateValidate {
            get {
                return ResourceManager.GetString("trPopUpdateValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقطة بيع.
        /// </summary>
        internal static string trPOS {
            get {
                return ResourceManager.GetString("trPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز نقطة البيع.
        /// </summary>
        internal static string trPosCode {
            get {
                return ResourceManager.GetString("trPosCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز نقطة البيع....
        /// </summary>
        internal static string trPosCodeHint {
            get {
                return ResourceManager.GetString("trPosCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم نقطة البيع.
        /// </summary>
        internal static string trPosName {
            get {
                return ResourceManager.GetString("trPosName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم نقطة البيع....
        /// </summary>
        internal static string trPosNameHint {
            get {
                return ResourceManager.GetString("trPosNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر....
        /// </summary>
        internal static string trPriceHint {
            get {
                return ResourceManager.GetString("trPriceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصائص.
        /// </summary>
        internal static string trProperties {
            get {
                return ResourceManager.GetString("trProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشتريات.
        /// </summary>
        internal static string trPurchases {
            get {
                return ResourceManager.GetString("trPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقارير.
        /// </summary>
        internal static string trReports {
            get {
                return ResourceManager.GetString("trReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبيعات.
        /// </summary>
        internal static string trSales {
            get {
                return ResourceManager.GetString("trSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل هنا للبدء بالبحث....
        /// </summary>
        internal static string trSearchHint {
            get {
                return ResourceManager.GetString("trSearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلوامات الثانوية.
        /// </summary>
        internal static string trSecondaryInformation {
            get {
                return ResourceManager.GetString("trSecondaryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الأساسية.
        /// </summary>
        internal static string trSectionData {
            get {
                return ResourceManager.GetString("trSectionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر اسم البنك.
        /// </summary>
        internal static string trSelectBankNameHint {
            get {
                return ResourceManager.GetString("trSelectBankNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر اسم الفرع.
        /// </summary>
        internal static string trSelectBranchHint {
            get {
                return ResourceManager.GetString("trSelectBranchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الفئة.
        /// </summary>
        internal static string trSelectCategorieHint {
            get {
                return ResourceManager.GetString("trSelectCategorieHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر نوع العنصر.
        /// </summary>
        internal static string trSelectItemTypeHint {
            get {
                return ResourceManager.GetString("trSelectItemTypeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر عمل....
        /// </summary>
        internal static string trSelectJobHint {
            get {
                return ResourceManager.GetString("trSelectJobHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر العنصر الأب.
        /// </summary>
        internal static string trSelectParentItemHint {
            get {
                return ResourceManager.GetString("trSelectParentItemHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الفرع.
        /// </summary>
        internal static string trSelectPosBranchHint {
            get {
                return ResourceManager.GetString("trSelectPosBranchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر اسم نقطة البيع.
        /// </summary>
        internal static string trSelectPosNameHint {
            get {
                return ResourceManager.GetString("trSelectPosNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الخصائص.
        /// </summary>
        internal static string trSelectProperties {
            get {
                return ResourceManager.GetString("trSelectProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر اسم الخاصية.
        /// </summary>
        internal static string trSelectPropertyNameHint {
            get {
                return ResourceManager.GetString("trSelectPropertyNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر أصغر وحدة.
        /// </summary>
        internal static string trSelectSmallestUnitHint {
            get {
                return ResourceManager.GetString("trSelectSmallestUnitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر اسم المخزن.
        /// </summary>
        internal static string trSelectStoreHint {
            get {
                return ResourceManager.GetString("trSelectStoreHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الوحدة.
        /// </summary>
        internal static string trSelectUnitHint {
            get {
                return ResourceManager.GetString("trSelectUnitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر اسم الوحدة.
        /// </summary>
        internal static string trSelestUnitNameHint {
            get {
                return ResourceManager.GetString("trSelestUnitNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعدادت.
        /// </summary>
        internal static string trSettings {
            get {
                return ResourceManager.GetString("trSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أصغر وحدة.
        /// </summary>
        internal static string trSmallestUnit {
            get {
                return ResourceManager.GetString("trSmallestUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اصغر وحدة.
        /// </summary>
        internal static string trSmallUnit {
            get {
                return ResourceManager.GetString("trSmallUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخزين.
        /// </summary>
        internal static string trStorage {
            get {
                return ResourceManager.GetString("trStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المخزن.
        /// </summary>
        internal static string trStore {
            get {
                return ResourceManager.GetString("trStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شيفرة المخزن....
        /// </summary>
        internal static string trStoreCodeHint {
            get {
                return ResourceManager.GetString("trStoreCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المخزن....
        /// </summary>
        internal static string trStoreNameHint {
            get {
                return ResourceManager.GetString("trStoreNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المخازن.
        /// </summary>
        internal static string trStores {
            get {
                return ResourceManager.GetString("trStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخواص الفرعية.
        /// </summary>
        internal static string trSubProperties {
            get {
                return ResourceManager.GetString("trSubProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل الخاصية الفرعية.
        /// </summary>
        internal static string trSubPropertiesHint {
            get {
                return ResourceManager.GetString("trSubPropertiesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزودون.
        /// </summary>
        internal static string trSuppliers {
            get {
                return ResourceManager.GetString("trSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الضرائب....
        /// </summary>
        internal static string trTaxesHint {
            get {
                return ResourceManager.GetString("trTaxesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة.
        /// </summary>
        internal static string trUnit {
            get {
                return ResourceManager.GetString("trUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة....
        /// </summary>
        internal static string trUnitHint {
            get {
                return ResourceManager.GetString("trUnitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الوحدة.
        /// </summary>
        internal static string trUnitName {
            get {
                return ResourceManager.GetString("trUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الوحدة....
        /// </summary>
        internal static string trUnitNameHint {
            get {
                return ResourceManager.GetString("trUnitNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدات.
        /// </summary>
        internal static string trUnits {
            get {
                return ResourceManager.GetString("trUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        internal static string trUpdate {
            get {
                return ResourceManager.GetString("trUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأعلى للسحب....
        /// </summary>
        internal static string trUpperLimitHint {
            get {
                return ResourceManager.GetString("trUpperLimitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم.
        /// </summary>
        internal static string trUser {
            get {
                return ResourceManager.GetString("trUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات المستخدم.
        /// </summary>
        internal static string trUserInformation {
            get {
                return ResourceManager.GetString("trUserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        internal static string trUserName {
            get {
                return ResourceManager.GetString("trUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم....
        /// </summary>
        internal static string trUserNameHint {
            get {
                return ResourceManager.GetString("trUserNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمون.
        /// </summary>
        internal static string trUsers {
            get {
                return ResourceManager.GetString("trUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستخدم.
        /// </summary>
        internal static string trUserType {
            get {
                return ResourceManager.GetString("trUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة.
        /// </summary>
        internal static string trValue {
            get {
                return ResourceManager.GetString("trValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة....
        /// </summary>
        internal static string trValueHint {
            get {
                return ResourceManager.GetString("trValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المورد.
        /// </summary>
        internal static string trVendor {
            get {
                return ResourceManager.GetString("trVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات العمل.
        /// </summary>
        internal static string trWorkHours {
            get {
                return ResourceManager.GetString("trWorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات العمل....
        /// </summary>
        internal static string trWorkHoursHint {
            get {
                return ResourceManager.GetString("trWorkHoursHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات العمل.
        /// </summary>
        internal static string trWorkInformation {
            get {
                return ResourceManager.GetString("trWorkInformation", resourceCulture);
            }
        }
    }
}
