//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_file {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_file() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POS.en_file", typeof(en_file).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string trAccNumber {
            get {
                return ResourceManager.GetString("trAccNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number....
        /// </summary>
        internal static string trAccNumberHint {
            get {
                return ResourceManager.GetString("trAccNumberHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        internal static string trAccounting {
            get {
                return ResourceManager.GetString("trAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string trAccounts {
            get {
                return ResourceManager.GetString("trAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string trAdd {
            get {
                return ResourceManager.GetString("trAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string trAddress {
            get {
                return ResourceManager.GetString("trAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address....
        /// </summary>
        internal static string trAdressHint {
            get {
                return ResourceManager.GetString("trAdressHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another Information.
        /// </summary>
        internal static string trAnotherInformation {
            get {
                return ResourceManager.GetString("trAnotherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +963.
        /// </summary>
        internal static string trAreaHint {
            get {
                return ResourceManager.GetString("trAreaHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string trBalance {
            get {
                return ResourceManager.GetString("trBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance....
        /// </summary>
        internal static string trBalanceHint {
            get {
                return ResourceManager.GetString("trBalanceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string trBankName {
            get {
                return ResourceManager.GetString("trBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name....
        /// </summary>
        internal static string trBankNameHint {
            get {
                return ResourceManager.GetString("trBankNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banks.
        /// </summary>
        internal static string trBanks {
            get {
                return ResourceManager.GetString("trBanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Information.
        /// </summary>
        internal static string trBaseInformation {
            get {
                return ResourceManager.GetString("trBaseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Code....
        /// </summary>
        internal static string trBranchCodeHint {
            get {
                return ResourceManager.GetString("trBranchCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        internal static string trBranches {
            get {
                return ResourceManager.GetString("trBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        internal static string trBranchName {
            get {
                return ResourceManager.GetString("trBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name....
        /// </summary>
        internal static string trBranchNameHint {
            get {
                return ResourceManager.GetString("trBranchNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string trCatalog {
            get {
                return ResourceManager.GetString("trCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie.
        /// </summary>
        internal static string trCategorie {
            get {
                return ResourceManager.GetString("trCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string trCategories {
            get {
                return ResourceManager.GetString("trCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string trCode {
            get {
                return ResourceManager.GetString("trCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code....
        /// </summary>
        internal static string trCodeHint {
            get {
                return ResourceManager.GetString("trCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string trCompany {
            get {
                return ResourceManager.GetString("trCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company....
        /// </summary>
        internal static string trCompanyHint {
            get {
                return ResourceManager.GetString("trCompanyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase POS.
        /// </summary>
        internal static string trCompanyName {
            get {
                return ResourceManager.GetString("trCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        internal static string trContactInformation {
            get {
                return ResourceManager.GetString("trContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string trCustomers {
            get {
                return ResourceManager.GetString("trCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string trDelete {
            get {
                return ResourceManager.GetString("trDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string trDetails {
            get {
                return ResourceManager.GetString("trDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details....
        /// </summary>
        internal static string trDetailsHint {
            get {
                return ResourceManager.GetString("trDetailsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email....
        /// </summary>
        internal static string trEmailHint {
            get {
                return ResourceManager.GetString("trEmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number can&apos;t be empty!.
        /// </summary>
        internal static string trEmptyAccNumToolTip {
            get {
                return ResourceManager.GetString("trEmptyAccNumToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select area.
        /// </summary>
        internal static string trEmptyAreaToolTip {
            get {
                return ResourceManager.GetString("trEmptyAreaToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance can not be empty.
        /// </summary>
        internal static string trEmptyBalanceToolTip {
            get {
                return ResourceManager.GetString("trEmptyBalanceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code can&apos;t be empty!.
        /// </summary>
        internal static string trEmptyCodeToolTip {
            get {
                return ResourceManager.GetString("trEmptyCodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name can&apos;t be empty!.
        /// </summary>
        internal static string trEmptyLastNameToolTip {
            get {
                return ResourceManager.GetString("trEmptyLastNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Property Name can not be empty.
        /// </summary>
        internal static string trEmptyMainPropNameToolTip {
            get {
                return ResourceManager.GetString("trEmptyMainPropNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the mobile number.
        /// </summary>
        internal static string trEmptyMobileToolTip {
            get {
                return ResourceManager.GetString("trEmptyMobileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not be empty.
        /// </summary>
        internal static string trEmptyNameToolTip {
            get {
                return ResourceManager.GetString("trEmptyNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be empty!.
        /// </summary>
        internal static string trEmptyPasswordToolTip {
            get {
                return ResourceManager.GetString("trEmptyPasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can&apos;t be empty!.
        /// </summary>
        internal static string trEmptyUserNameToolTip {
            get {
                return ResourceManager.GetString("trEmptyUserNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is not valid.
        /// </summary>
        internal static string trErrorEmailToolTip {
            get {
                return ResourceManager.GetString("trErrorEmailToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name....
        /// </summary>
        internal static string trFirstNameHint {
            get {
                return ResourceManager.GetString("trFirstNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string trHome {
            get {
                return ResourceManager.GetString("trHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Smallest.
        /// </summary>
        internal static string trIsSmallest {
            get {
                return ResourceManager.GetString("trIsSmallest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Smallest.
        /// </summary>
        internal static string trIsSmallestHint {
            get {
                return ResourceManager.GetString("trIsSmallestHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string trItems {
            get {
                return ResourceManager.GetString("trItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        internal static string trJob {
            get {
                return ResourceManager.GetString("trJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job...
        /// </summary>
        internal static string trJobHint {
            get {
                return ResourceManager.GetString("trJobHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string trLastName {
            get {
                return ResourceManager.GetString("trLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name....
        /// </summary>
        internal static string trLastNameHint {
            get {
                return ResourceManager.GetString("trLastNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Information.
        /// </summary>
        internal static string trLoginInformation {
            get {
                return ResourceManager.GetString("trLoginInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Property.
        /// </summary>
        internal static string trMainProperty {
            get {
                return ResourceManager.GetString("trMainProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Main Property.
        /// </summary>
        internal static string trMainPropertyHint {
            get {
                return ResourceManager.GetString("trMainPropertyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string trMenu {
            get {
                return ResourceManager.GetString("trMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string trMobile {
            get {
                return ResourceManager.GetString("trMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile....
        /// </summary>
        internal static string trMobileHint {
            get {
                return ResourceManager.GetString("trMobileHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        internal static string trMoreInformation {
            get {
                return ResourceManager.GetString("trMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string trName {
            get {
                return ResourceManager.GetString("trName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name....
        /// </summary>
        internal static string trNameHint {
            get {
                return ResourceManager.GetString("trNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note....
        /// </summary>
        internal static string trNoteHint {
            get {
                return ResourceManager.GetString("trNoteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Payment method....
        /// </summary>
        internal static string trPamentMethodHint {
            get {
                return ResourceManager.GetString("trPamentMethodHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Parent Item.
        /// </summary>
        internal static string trParentCategorieHint {
            get {
                return ResourceManager.GetString("trParentCategorieHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password....
        /// </summary>
        internal static string trPasswordHint {
            get {
                return ResourceManager.GetString("trPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone....
        /// </summary>
        internal static string trPhoneHint {
            get {
                return ResourceManager.GetString("trPhoneHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        internal static string trPOS {
            get {
                return ResourceManager.GetString("trPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Code.
        /// </summary>
        internal static string trPosCode {
            get {
                return ResourceManager.GetString("trPosCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Code....
        /// </summary>
        internal static string trPosCodeHint {
            get {
                return ResourceManager.GetString("trPosCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Name.
        /// </summary>
        internal static string trPosName {
            get {
                return ResourceManager.GetString("trPosName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Name....
        /// </summary>
        internal static string trPosNameHint {
            get {
                return ResourceManager.GetString("trPosNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string trProperties {
            get {
                return ResourceManager.GetString("trProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        internal static string trPurchases {
            get {
                return ResourceManager.GetString("trPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string trReports {
            get {
                return ResourceManager.GetString("trReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string trSales {
            get {
                return ResourceManager.GetString("trSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Here To Start Search .....
        /// </summary>
        internal static string trSearchHint {
            get {
                return ResourceManager.GetString("trSearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Information.
        /// </summary>
        internal static string trSecondaryInformation {
            get {
                return ResourceManager.GetString("trSecondaryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Data.
        /// </summary>
        internal static string trSectionData {
            get {
                return ResourceManager.GetString("trSectionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bank Name.
        /// </summary>
        internal static string trSelectBankNameHint {
            get {
                return ResourceManager.GetString("trSelectBankNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Branch Name.
        /// </summary>
        internal static string trSelectBranchHint {
            get {
                return ResourceManager.GetString("trSelectBranchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Job ....
        /// </summary>
        internal static string trSelectJobHint {
            get {
                return ResourceManager.GetString("trSelectJobHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Branch....
        /// </summary>
        internal static string trSelectPosBranchHint {
            get {
                return ResourceManager.GetString("trSelectPosBranchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select POS Name.
        /// </summary>
        internal static string trSelectPosNameHint {
            get {
                return ResourceManager.GetString("trSelectPosNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Property Name.
        /// </summary>
        internal static string trSelectPropertyNameHint {
            get {
                return ResourceManager.GetString("trSelectPropertyNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Smallest Unit....
        /// </summary>
        internal static string trSelectSmallestUnitHint {
            get {
                return ResourceManager.GetString("trSelectSmallestUnitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Store Name.
        /// </summary>
        internal static string trSelectStoreHint {
            get {
                return ResourceManager.GetString("trSelectStoreHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Unit Name.
        /// </summary>
        internal static string trSelestUnitNameHint {
            get {
                return ResourceManager.GetString("trSelestUnitNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string trSettings {
            get {
                return ResourceManager.GetString("trSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smallest Unit.
        /// </summary>
        internal static string trSmallestUnit {
            get {
                return ResourceManager.GetString("trSmallestUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string trStorage {
            get {
                return ResourceManager.GetString("trStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Code....
        /// </summary>
        internal static string trStoreCodeHint {
            get {
                return ResourceManager.GetString("trStoreCodeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name....
        /// </summary>
        internal static string trStoreNameHint {
            get {
                return ResourceManager.GetString("trStoreNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        internal static string trStores {
            get {
                return ResourceManager.GetString("trStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Properties.
        /// </summary>
        internal static string trSubProperties {
            get {
                return ResourceManager.GetString("trSubProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Sub Property.
        /// </summary>
        internal static string trSubPropertiesHint {
            get {
                return ResourceManager.GetString("trSubPropertiesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        internal static string trSuppliers {
            get {
                return ResourceManager.GetString("trSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes....
        /// </summary>
        internal static string trTaxesHint {
            get {
                return ResourceManager.GetString("trTaxesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name.
        /// </summary>
        internal static string trUnitName {
            get {
                return ResourceManager.GetString("trUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name....
        /// </summary>
        internal static string trUnitNameHint {
            get {
                return ResourceManager.GetString("trUnitNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string trUnits {
            get {
                return ResourceManager.GetString("trUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string trUpdate {
            get {
                return ResourceManager.GetString("trUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Infomration.
        /// </summary>
        internal static string trUserInformation {
            get {
                return ResourceManager.GetString("trUserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string trUserName {
            get {
                return ResourceManager.GetString("trUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name....
        /// </summary>
        internal static string trUserNameHint {
            get {
                return ResourceManager.GetString("trUserNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string trUsers {
            get {
                return ResourceManager.GetString("trUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        internal static string trUserType {
            get {
                return ResourceManager.GetString("trUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Hours.
        /// </summary>
        internal static string trWorkHours {
            get {
                return ResourceManager.GetString("trWorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Hours....
        /// </summary>
        internal static string trWorkHoursHint {
            get {
                return ResourceManager.GetString("trWorkHoursHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Information.
        /// </summary>
        internal static string trWorkInformation {
            get {
                return ResourceManager.GetString("trWorkInformation", resourceCulture);
            }
        }
    }
}
