//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_file {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_file() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POS.en_file", typeof(en_file).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        internal static string trAccounting {
            get {
                return ResourceManager.GetString("trAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string trAccounts {
            get {
                return ResourceManager.GetString("trAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string trAdd {
            get {
                return ResourceManager.GetString("trAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address....
        /// </summary>
        internal static string trAdressHint {
            get {
                return ResourceManager.GetString("trAdressHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another Infomation.
        /// </summary>
        internal static string trAnotherInfomation {
            get {
                return ResourceManager.GetString("trAnotherInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area....
        /// </summary>
        internal static string trAreaHint {
            get {
                return ResourceManager.GetString("trAreaHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance....
        /// </summary>
        internal static string trBalanceHint {
            get {
                return ResourceManager.GetString("trBalanceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banks.
        /// </summary>
        internal static string trBanks {
            get {
                return ResourceManager.GetString("trBanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Infomation.
        /// </summary>
        internal static string trBaseInformation {
            get {
                return ResourceManager.GetString("trBaseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        internal static string trBranches {
            get {
                return ResourceManager.GetString("trBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string trCatalog {
            get {
                return ResourceManager.GetString("trCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company....
        /// </summary>
        internal static string trCompanyHint {
            get {
                return ResourceManager.GetString("trCompanyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase POS.
        /// </summary>
        internal static string trCompanyName {
            get {
                return ResourceManager.GetString("trCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Infomation.
        /// </summary>
        internal static string trContactInformation {
            get {
                return ResourceManager.GetString("trContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string trCustomers {
            get {
                return ResourceManager.GetString("trCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string trDelete {
            get {
                return ResourceManager.GetString("trDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details....
        /// </summary>
        internal static string trDetailsHint {
            get {
                return ResourceManager.GetString("trDetailsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email....
        /// </summary>
        internal static string trEmailHint {
            get {
                return ResourceManager.GetString("trEmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string trHome {
            get {
                return ResourceManager.GetString("trHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string trMenu {
            get {
                return ResourceManager.GetString("trMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile....
        /// </summary>
        internal static string trMobileHint {
            get {
                return ResourceManager.GetString("trMobileHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name....
        /// </summary>
        internal static string trNameHint {
            get {
                return ResourceManager.GetString("trNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note....
        /// </summary>
        internal static string trNoteHint {
            get {
                return ResourceManager.GetString("trNoteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Payment method....
        /// </summary>
        internal static string trPamentMethodHint {
            get {
                return ResourceManager.GetString("trPamentMethodHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone....
        /// </summary>
        internal static string trPhoneHint {
            get {
                return ResourceManager.GetString("trPhoneHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        internal static string trPOS {
            get {
                return ResourceManager.GetString("trPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        internal static string trPurchases {
            get {
                return ResourceManager.GetString("trPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string trReports {
            get {
                return ResourceManager.GetString("trReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string trSales {
            get {
                return ResourceManager.GetString("trSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Here To Start Search .....
        /// </summary>
        internal static string trSearchHint {
            get {
                return ResourceManager.GetString("trSearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Data.
        /// </summary>
        internal static string trSectionData {
            get {
                return ResourceManager.GetString("trSectionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string trSettings {
            get {
                return ResourceManager.GetString("trSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string trStorage {
            get {
                return ResourceManager.GetString("trStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        internal static string trStores {
            get {
                return ResourceManager.GetString("trStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        internal static string trSuppliers {
            get {
                return ResourceManager.GetString("trSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string trUnits {
            get {
                return ResourceManager.GetString("trUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string trUpdate {
            get {
                return ResourceManager.GetString("trUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string trUserName {
            get {
                return ResourceManager.GetString("trUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string trUsers {
            get {
                return ResourceManager.GetString("trUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        internal static string trUserType {
            get {
                return ResourceManager.GetString("trUserType", resourceCulture);
            }
        }
    }
}
