//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupObject
    {
        public int id { get; set; }
        public Nullable<int> groupId { get; set; }
        public Nullable<int> objectId { get; set; }
        public string notes { get; set; }
        public bool addOb { get; set; }
        public bool updateOb { get; set; }
        public bool deleteOb { get; set; }
        public bool showOb { get; set; }
        public Nullable<bool> reportOb { get; set; }
        public Nullable<byte> levelOb { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<int> createUserId { get; set; }
        public Nullable<int> updateUserId { get; set; }
        public Nullable<int> isActive { get; set; }
    
        public virtual groups groups { get; set; }
        public virtual objects objects { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
