//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramDetails
    {
        public int id { get; set; }
        public string programName { get; set; }
        public int branchCount { get; set; }
        public int posCount { get; set; }
        public int userCount { get; set; }
        public int vendorCount { get; set; }
        public int customerCount { get; set; }
        public int itemCount { get; set; }
        public int saleinvCount { get; set; }
        public Nullable<int> programIncId { get; set; }
        public Nullable<int> versionIncId { get; set; }
        public string versionName { get; set; }
        public int storeCount { get; set; }
        public string packageSaleCode { get; set; }
        public string customerServerCode { get; set; }
        public Nullable<System.DateTime> expireDate { get; set; }
        public Nullable<bool> isOnlineServer { get; set; }
        public string packageNumber { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    }
}
