//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class serials
    {
        public int serialId { get; set; }
        public Nullable<int> itemId { get; set; }
        public string serialNum { get; set; }
        public Nullable<byte> isActive { get; set; }
    
        public virtual items items { get; set; }
    }
}
